# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 17:46
from __future__ import unicode_literals

import demoslogic.premises.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', demoslogic.premises.models.TrimmedCharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorizationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('last_voted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last voted')),
                ('value', models.IntegerField(choices=[(1, 'Not accurate at all or very little'), (2, 'Barely useful'), (3, 'Useful'), (4, 'Completely accurate')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', demoslogic.premises.models.TrimmedCharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('staged', models.DateTimeField(blank=True, null=True)),
                ('sentence', demoslogic.premises.models.TrimmedCharField(default='', max_length=250, unique=True)),
                ('premise_type', models.IntegerField(choices=[(1, 'Categorization'), (2, 'Comparison'), (3, 'Empirical claim'), (4, 'Proposal')], default=1)),
                ('key_complement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Adjective')),
                ('key_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_object', to='premises.Noun')),
            ],
            options={
                'get_latest_by': 'pub_date',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', demoslogic.premises.models.TrimmedCharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='premise',
            name='key_predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Verb'),
        ),
        migrations.AddField(
            model_name='premise',
            name='key_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_subject', to='premises.Noun'),
        ),
        migrations.AddField(
            model_name='premise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorizationvote',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premises.Premise'),
        ),
        migrations.AddField(
            model_name='categorizationvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
