# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategorizationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('staged', models.DateTimeField(blank=True, null=True)),
                ('last_voted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last voted')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('staged', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(default='', max_length=200)),
                ('predicate', models.CharField(default='', max_length=200)),
                ('object', models.CharField(blank=True, default='', max_length=200)),
                ('complement', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categorizationvote',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premises.Premise'),
        ),
        migrations.AddField(
            model_name='categorizationvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
