# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Premise',
        ),
        migrations.RenameField(
            model_name='premise',
            old_name='question_text',
            new_name='text',
        ),
    ]
