# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='key_indirect_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_indirect_object', to='premises.Noun'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_predicate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Verb'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (3, 'Comparison'), (4, 'Deduction'), (5, 'Diagnosis'), (6, 'Proposal')], default=1),
        ),
        migrations.AlterField(
            model_name='premisevote',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='premise',
            unique_together=set([('premise_type', 'key_subject', 'key_predicate', 'key_object', 'key_complement', 'key_indirect_object')]),
        ),
    ]
