# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0002_auto_20161113_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premise',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='premise',
            unique_together=set([('premise_type', 'key_subject', 'key_predicate', 'key_object', 'key_complement')]),
        ),
    ]
