# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0003_auto_20161023_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizationvote',
            name='value',
            field=models.IntegerField(choices=[(0, 'Not accurate at all or very little'), (1, 'Barely useful'), (2, 'Useful'), (3, 'Completely accurate')], validators=[django.core.validators.MaxValueValidator(3, message='Vote value above maximum')]),
        ),
    ]
