# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 22:42
from __future__ import unicode_literals

import demoslogic.premises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0003_auto_20161126_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Collection'), (3, 'Comparison'), (7, 'Deduction'), (4, 'Deduction'), (5, 'Diagnosis'), (6, 'Proposal')], default=1),
        ),
        migrations.AlterField(
            model_name='premise',
            name='sentence',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=250),
        ),
    ]
