# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0003_auto_20161015_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='CategorizationVote',
        ),
    ]
