# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0004_auto_20161205_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Collection'), (3, 'Comparison'), (7, 'Relation'), (5, 'Diagnosis'), (6, 'Proposal')], default=1),
        ),
    ]
