# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0004_auto_20161119_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premise',
            options={'get_latest_by': 'pub_date'},
        ),
    ]
