# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0004_auto_20161023_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizationvote',
            name='value',
            field=models.IntegerField(choices=[(1, 'Not accurate at all or very little'), (2, 'Barely useful'), (3, 'Useful'), (4, 'Completely accurate')], validators=[django.core.validators.MaxValueValidator(4, message='Vote value above maximum')]),
        ),
    ]
