# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161002_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premise',
            name='issubjectcomplement',
        ),
        migrations.AddField(
            model_name='premise',
            name='hasobject',
            field=models.BooleanField(default=False),
        ),
    ]
