# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0005_auto_20161120_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Description'), (3, 'Comparison'), (4, 'Diagnosis'), (5, 'Proposal')], default=1),
        ),
    ]
