# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0006_auto_20161122_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Ascription'), (3, 'Comparison'), (4, 'Diagnosis'), (5, 'Proposal')], default=1),
        ),
    ]
