# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0006_auto_20161206_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Collection'), (3, 'Comparison'), (4, 'Relation'), (5, 'Diagnosis')], default=1),
        ),
    ]
