# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 05:53
from __future__ import unicode_literals

import demoslogic.premises.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0007_auto_20161031_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='complement',
            field=demoslogic.premises.models.TrimmedCharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='premise',
            name='object',
            field=demoslogic.premises.models.TrimmedCharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='premise',
            name='predicate',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='premise',
            name='subject',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=200),
        ),
    ]
