# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0007_auto_20161122_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='key_indirect_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_indirect_object', to='premises.Noun'),
        ),
    ]
