# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0008_auto_20161209_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='key_complement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premises.Adjective'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_indirect_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_indirect_object', to='premises.Noun'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_object', to='premises.Noun'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_predicate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premises.Verb'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_subject', to='premises.Noun'),
        ),
    ]
