# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0008_premise_key_indirect_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Comparison'), (3, 'Deduction'), (4, 'Diagnosis'), (5, 'Proposal')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='premise',
            unique_together=set([('premise_type', 'key_subject', 'key_predicate', 'key_object', 'key_complement', 'key_indirect_object')]),
        ),
    ]
