# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:13
from __future__ import unicode_literals

import demoslogic.premises.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0009_remove_categorizationvote_staged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', demoslogic.premises.models.TrimmedCharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', demoslogic.premises.models.TrimmedCharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', demoslogic.premises.models.TrimmedCharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='premise',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='object',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='predicate',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='subject',
        ),
        migrations.AddField(
            model_name='premise',
            name='sentence',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='premise',
            name='key_complement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Complement'),
        ),
        migrations.AddField(
            model_name='premise',
            name='key_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_object', to='premises.Noun'),
        ),
        migrations.AddField(
            model_name='premise',
            name='key_predicate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Verb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premise',
            name='key_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_subject', to='premises.Noun'),
            preserve_default=False,
        ),
    ]
