# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0009_auto_20161229_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='key_indirect_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_indirect_object', to='premises.Noun'),
        ),
    ]
