# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0009_auto_20161122_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizationvote',
            name='value',
            field=models.IntegerField(choices=[(1, ''), (2, '')], default=1),
        ),
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (3, 'Comparison'), (4, 'Deduction'), (5, 'Diagnosis'), (6, 'Proposal')], default=1),
        ),
    ]
