# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0010_auto_20161125_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizationvote',
            name='value',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, '')], default=1),
        ),
    ]
