# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0010_auto_20161112_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complement',
            old_name='verb',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='noun',
            old_name='noun',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='verb',
            new_name='name',
        ),
    ]
