# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0011_auto_20161230_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='sentence',
            field=models.CharField(default='', max_length=250),
        ),
    ]
