# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0011_auto_20161112_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verb',
            new_name='Predicate',
        ),
    ]
