# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0012_auto_20161230_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Collection'), (3, 'Comparison'), (4, 'Correlation'), (5, 'Existance')], default=1),
        ),
    ]
