# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 18:16
from __future__ import unicode_literals

import demoslogic.premises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0012_auto_20161112_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='premise_type',
            field=models.IntegerField(choices=[(1, 'Categorization'), (2, 'Comparison'), (3, 'Empirical claim'), (4, 'Proposal')], default=1),
        ),
        migrations.AlterField(
            model_name='premise',
            name='sentence',
            field=demoslogic.premises.models.TrimmedCharField(blank=True, default='', max_length=250),
        ),
    ]
