# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 17:04
from __future__ import unicode_literals

import demoslogic.premises.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0013_auto_20161112_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complement',
            name='name',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='noun',
            name='name',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='name',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_complement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Complement'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_object', to='premises.Noun'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_predicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='premises.Predicate'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='key_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='key_subject', to='premises.Noun'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='sentence',
            field=demoslogic.premises.models.TrimmedCharField(blank=True, default='', max_length=250, unique=True),
        ),
    ]
