# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 11:54
from __future__ import unicode_literals

import demoslogic.premises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0015_auto_20170102_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='name',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='noun',
            name='name',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='premise',
            name='sentence',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='verb',
            name='name',
            field=demoslogic.premises.models.TrimmedCharField(default='', max_length=100, unique=True),
        ),
    ]
