# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0016_auto_20170102_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjective',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='adjective',
            name='user',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='user',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='user',
        ),
    ]
