# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0007_auto_20161031_1217'),
        ('arguments', '0002_argumentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='conclusion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='premises.Premise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='argument',
            name='premise1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='premise1', to='premises.Premise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='argument',
            name='premise2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='premise2', to='premises.Premise'),
            preserve_default=False,
        ),
    ]
