# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0003_auto_20161114_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argument',
            old_name='premise1_if_clauses',
            new_name='premise1_if',
        ),
        migrations.RenameField(
            model_name='argument',
            old_name='premise2_if_clauses',
            new_name='premise2_if',
        ),
    ]
