# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0003_auto_20161031_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='aim',
            field=models.IntegerField(choices=[(1, 'To support the positive version of the conclusion.'), (2, 'To support the negative version of the conclusion.'), (3, 'To point why a decision on the matter is required soon.'), (4, 'To point out missing knowledge on the matter.')], default=1),
        ),
    ]
