# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0005_auto_20161123_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentvote',
            name='value',
            field=models.IntegerField(choices=[(0, 'completely invalid'), (1, 'weak'), (2, 'strong'), (3, 'completely valid')], default=1),
        ),
    ]
