# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0004_auto_20161205_2342'),
        ('arguments', '0006_auto_20161126_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='argument',
            unique_together=set([('premise1_if', 'premise1', 'premise2', 'premise2_if', 'aim', 'conclusion')]),
        ),
    ]
