# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0008_auto_20161209_1553'),
        ('arguments', '0008_argument_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='premise3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premise3', to='premises.Premise'),
        ),
        migrations.AddField(
            model_name='argument',
            name='premise3_if',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='aim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='premise2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premise2', to='premises.Premise'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='premise2_if',
            field=models.IntegerField(null=True),
        ),
    ]
