# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0011_auto_20161227_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='sentence',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
