# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161002_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='complement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='premise',
            name='issubjectcomplement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premise',
            name='object',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='premise',
            name='predicate',
            field=models.CharField(default='no_predicate', max_length=200),
        ),
        migrations.AlterField(
            model_name='premise',
            name='subject',
            field=models.CharField(default='no_subject', max_length=200),
        ),
    ]
