# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161002_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premise',
            name='hasobject',
        ),
    ]
