# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_premise_hasobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='complement',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='premise',
            name='object',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='premise',
            name='predicate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='premise',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
