# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160927_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
