# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='premises',
            new_name='statement',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='premise_version',
            new_name='version',
        ),
    ]
