# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0002_auto_20161228_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencevote',
            name='value',
            field=models.IntegerField(choices=[(0, 'neither trustworthy nor relevant'), (1, 'trustworthy, but not relevant'), (2, 'relevant, but not trustworthy'), (3, 'both relevant and trustworthy')], default=1),
        ),
    ]
